<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240817171815 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, startedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, endedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D044D5D4F675F31B ON session (author_id)');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review ADD session_id INT NOT NULL');
        $this->addSql('ALTER TABLE review ALTER flashcard_id SET NOT NULL');
        $this->addSql('ALTER TABLE review ALTER user_id SET NOT NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_794381C6613FECDF ON review (session_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4F675F31B');
        $this->addSql('DROP TABLE session');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6613FECDF');
        $this->addSql('DROP INDEX IDX_794381C6613FECDF');
        $this->addSql('ALTER TABLE review DROP session_id');
        $this->addSql('ALTER TABLE review ALTER flashcard_id DROP NOT NULL');
        $this->addSql('ALTER TABLE review ALTER user_id DROP NOT NULL');
    }
}
